### ISSUE TITLE
CB2 stays half open forever after being tripped open once

### ISSUE THREAD

**Issue by v-yarotsky** [prognostikos/cb2#1]
Hi
It looks like CB2 can never become fully closed after being opened once. [Here's a failing test](https://gist.github.com/v-yarotsky/89fdc743a7e17e98f502).

The rolling window strategy's [`#half_open?`](https://github.com/pedro/cb2/blob/41481eba7bd8b8fcd097cf89d31838dc16a7a2ad/lib/cb2/strategies/rolling_window.rb#L22) is pretty much the opposite of `#open?`, which is not what it is supposed to represent.

I was thinking of having a `success` callback in a strategy, which would reset `last_open` if the circuit breaker is currently half-open. This would solve the issue in a single-threaded case, although in a hacky manner, but there are going to be issues with concurrent clients (cranking up number of `WORKERS` in the test to 50 or so exposes the issue).

**Comment by jphenow** [comment]
I think this is closeable now?

**Comment by victorhazbun** [comment]
@pedro

**Comment by prognostikos** [comment]
Looks like this was fixed in [v0.0.3](https://github.com/prognostikos/cb2/releases/tag/v0.0.3)
