### ISSUE TITLE
Redis 4 support?

### ISSUE THREAD

**Issue by edelgado** [prognostikos/cb2#10]
Hi @pedro! Any plans to support Redis 4? I see that at the moment it's only 3.x support.

**Comment by edelgado** [comment]
A cursory look at redis calls seems to indicate that this would work just fine with Redis 4 :-)

**Comment by talhashoaib** [comment]
@edelgado I forked and updated with newer version maybe I will add some more functionality soon. 
https://github.com/talhashoaib/cb2

**Comment by prognostikos** [comment]
Redis 4 & 5 are now supported on master and we'll release a new gem soon.
