### ISSUE TITLE
Maintained fork

### ISSUE THREAD

**Issue by prognostikos** [prognostikos/cb2#14]
FWIW, I am maintaining a fork at https://github.com/prognostikos/cb2 as we use this in production.

I'd be happy to take over the gem if that's an option, or otherwise contribute back to this repo with PRs etc.

**Comment by pedro** [comment]
@prognostikos wow, looks great! I'd love to have you take it over.

how do we do this, think I just need to add you as gem owner, and then transfer this repo to your account? we could just update url in gemspec/etc but it seems awesome to have `pedro/cb2` redirect to the latest! let me know your thoughts.

thank you! <3

**Comment by prognostikos** [comment]
@pedro I agree that we should ensure this repo redirects. According to [the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) transferring will do the right thing. I have renamed my forked repo to `cb2-fork` so that you can use the `cb2` repo name in the transfer. I'm [rohrer](https://rubygems.org/profiles/rohrer) on rubygems.

Thank you for the great gem, it's been running smoothly for us for many years now.

**Comment by prognostikos** [comment]
I'm actually not sure that renaming my fork will make `cb2` available as it is currently redirecting to the new name, but I guess we'll see when you try. Otherwise feel free to pick another repo name.

**Comment by pedro** [comment]
oops, finally got to this!

funny, I'm getting an unhandled 422 from GH's api:

        "error": "prognostikos already has a repository in the pedro/cb2 network"

I guess rename or delete the fork? 🤔

**Comment by prognostikos** [comment]
I've deleted the fork, give it another try.

**Comment by pedro** [comment]
nice, think it got through this time!

feel free to update with your changes/tweak anything/etc and let's get to the gem ownership!

**Comment by prognostikos** [comment]
Looks like it worked!

I'll update from my local repo tomorrow (CEST).

**Comment by prognostikos** [comment]
I've done a bit more tidying up, added a changelog and pushed my changes.

**Comment by prognostikos** [comment]
@pedro would love to get this over the line, is there anything you need from me?

**Comment by dancallaghan** [comment]
Is this preventing a new rubygem version being published?

**Comment by prognostikos** [comment]
> Is this preventing a new rubygem version being published?

@dancallaghan yes, I haven't yet gotten access to push the gem from @pedro. For now we're pulling it from here:

```ruby
gem "cb2", git: "https://github.com/prognostikos/cb2", ref: "9c6026fb2185b830a57c49f0424ffe677a79a51f"
```

**Comment by pedro** [comment]
oops, this looks great! let's make sure you can push @prognostikos 

I'm not seeing an option to add you in Rubygems, guess I just need to push the latest manifest?

**Comment by prognostikos** [comment]
@pedro I think you should be able to add me (`rohrer`) at https://rubygems.org/gems/cb2/owners

**Comment by pedro** [comment]
ahh, doh! added :+1:

**Comment by prognostikos** [comment]
I can confirm I now have access, thanks @pedro! I'll release and push 0.0.4 tomorrow.

**Comment by dancallaghan** [comment]
Awesome, thanks :)

**Comment by prognostikos** [comment]
Version 0.0.4 has been released. Thanks again for this gem @pedro, it has been working well for us for many years.
