### ISSUE TITLE
actual state of the gem

### ISSUE THREAD

**Issue by luizkowalski** [prognostikos/cb2#4]
what is the current state of this gem?
the last commit dates from a year ago...is it still maintained or its just "done"?

**Comment by luizkowalski** [comment]
follow up?

**Comment by luizkowalski** [comment]
cc @pedro?

**Comment by pedro** [comment]
wow, can't believe I wasn't getting notifications for this repo for some reason, prob when I changed emails here on GH. Weird! Sorry for the trouble.

Will take a look at the open issues – basically I'm not running an app that uses a breaker at this point so this repo is stale, yes! I'll update this if this ever changes.

Thanks,

**Comment by prognostikos** [comment]
FWIW we've been running this in production for many years without issues. I would call it "done", at least for our needs.
